/**
 * Source: Sites carrières directs des grandes entreprises
 * Récupère les offres d'alternance directement depuis les pages carrières
 */

// Liste des 100 plus grandes entreprises françaises avec leurs URLs carrières
const COMPANIES = [
  // CAC 40
  { name: 'LVMH', careers: 'https://careers.lvmh.com/search-jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'TotalEnergies', careers: 'https://jobs.totalenergies.com/jobs', keywords: ['alternance', 'apprentice'] },
  { name: 'Sanofi', careers: 'https://sanofi.wd3.myworkdayjobs.com/SanofiCareers', keywords: ['apprenticeship', 'alternance'] },
  { name: 'Airbus', careers: 'https://ag.wd3.myworkdayjobs.com/Airbus', keywords: ['apprentice', 'alternance'] },
  { name: 'L\'Oréal', careers: 'https://careers.loreal.com/global/en/search-results', keywords: ['apprentice', 'alternance'] },
  { name: 'Schneider Electric', careers: 'https://careers.se.com/jobs', keywords: ['apprentice', 'alternance'] },
  { name: 'BNP Paribas', careers: 'https://careers.bnpparibas/jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'AXA', careers: 'https://careers.axa.com/global/en/search-results', keywords: ['alternance', 'apprentice'] },
  { name: 'Société Générale', careers: 'https://careers.societegenerale.com/fr/search-jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'Crédit Agricole', careers: 'https://www.credit-agricole.jobs/rejoignez-nous', keywords: ['alternance', 'apprentissage'] },
  { name: 'Orange', careers: 'https://orange.jobs/jobs/search', keywords: ['alternance', 'apprentissage'] },
  { name: 'Engie', careers: 'https://www.engie.com/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Saint-Gobain', careers: 'https://www.saint-gobain.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Carrefour', careers: 'https://www.carrefour.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Danone', careers: 'https://careers.danone.com/global/en/search-results', keywords: ['apprentice', 'alternance'] },
  { name: 'Pernod Ricard', careers: 'https://careers.pernod-ricard.com/global/en/search-results', keywords: ['apprentice', 'alternance'] },
  { name: 'Michelin', careers: 'https://recrutement.michelin.fr/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Legrand', careers: 'https://www.legrandgroup.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Thales', careers: 'https://careers.thalesgroup.com/global/en/search-results', keywords: ['apprentice', 'alternance'] },
  { name: 'Dassault Systèmes', careers: 'https://careers.3ds.com/jobs', keywords: ['apprentice', 'alternance'] },

  // SBF 120 & grandes entreprises
  { name: 'Capgemini', careers: 'https://www.capgemini.com/fr-fr/carrieres/offres-emploi', keywords: ['alternance', 'apprentissage'] },
  { name: 'Atos', careers: 'https://jobs.atos.net/search-jobs', keywords: ['alternance', 'apprentice'] },
  { name: 'Sopra Steria', careers: 'https://www.soprasteria.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Dassault Aviation', careers: 'https://www.dassault-aviation.com/fr/groupe/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Safran', careers: 'https://www.safran-group.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Bouygues', careers: 'https://careers.bouygues.com/fr/search-jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'Vinci', careers: 'https://www.vinci.com/vinci.nsf/fr/carrieres/pages/offres.htm', keywords: ['alternance', 'apprentissage'] },
  { name: 'Eiffage', careers: 'https://www.eiffage.com/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Veolia', careers: 'https://www.veolia.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Suez', careers: 'https://www.suez.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },

  // Tech & Digital
  { name: 'Atos', careers: 'https://jobs.atos.net/search-jobs', keywords: ['alternance', 'apprentice'] },
  { name: 'OVHcloud', careers: 'https://corporate.ovhcloud.com/fr/careers/jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'Deezer', careers: 'https://www.deezer.com/fr/company/jobs', keywords: ['internship', 'alternance'] },
  { name: 'BlaBlaCar', careers: 'https://blog.blablacar.com/careers', keywords: ['internship', 'alternance'] },
  { name: 'Criteo', careers: 'https://careers.criteo.com/search-jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Doctolib', careers: 'https://careers.doctolib.com/jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'Mirakl', careers: 'https://careers.mirakl.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Alan', careers: 'https://alan.com/fr/carriere', keywords: ['alternance', 'apprentissage'] },
  { name: 'Back Market', careers: 'https://www.backmarket.com/fr-fr/careers', keywords: ['alternance', 'apprentice'] },
  { name: 'Contentsquare', careers: 'https://contentsquare.com/careers/', keywords: ['internship', 'apprentice'] },

  // Retail & E-commerce
  { name: 'Decathlon', careers: 'https://recrutement.decathlon.fr/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Leroy Merlin', careers: 'https://www.leroymerlin.fr/offres-emploi', keywords: ['alternance', 'apprentissage'] },
  { name: 'Auchan', careers: 'https://www.auchan-recrute.fr/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Fnac Darty', careers: 'https://www.fnacdarty.com/carriere/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cdiscount', careers: 'https://recrutement.cdiscount.com/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Boulanger', careers: 'https://www.boulanger.com/info/recrutement', keywords: ['alternance', 'apprentissage'] },

  // Banque & Assurance
  { name: 'BPCE', careers: 'https://www.groupebpce.com/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Crédit Mutuel', careers: 'https://www.creditmutuel.fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'La Banque Postale', careers: 'https://www.labanquepostale.fr/recrutement/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Allianz', careers: 'https://careers.allianz.com/fr/search-results', keywords: ['alternance', 'apprentice'] },
  { name: 'Generali', careers: 'https://careers.generali.com/fr/search-results', keywords: ['alternance', 'apprentice'] },
  { name: 'Axa France', careers: 'https://recrutement.axa.fr/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Groupama', careers: 'https://www.groupama.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'MAIF', careers: 'https://www.maif.fr/recrutement/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'MACIF', careers: 'https://www.macif.fr/recrutement/offres', keywords: ['alternance', 'apprentissage'] },

  // Automobile
  { name: 'Renault', careers: 'https://www.renaultgroup.com/talents/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Stellantis', careers: 'https://www.stellantis.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Valeo', careers: 'https://www.valeo.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Faurecia', careers: 'https://www.forvia.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Plastic Omnium', careers: 'https://www.plasticomnium.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },

  // Aéronautique & Défense
  { name: 'Naval Group', careers: 'https://www.naval-group.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Nexter', careers: 'https://www.nexter-group.fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'MBDA', careers: 'https://www.mbda-systems.com/careers/job-offers', keywords: ['apprentice', 'alternance'] },
  { name: 'Latécoère', careers: 'https://www.latecoere.aero/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },

  // Énergie
  { name: 'EDF', careers: 'https://www.edf.fr/recrutement/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Orano', careers: 'https://www.orano.group/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Framatome', careers: 'https://www.framatome.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },

  // Télécoms
  { name: 'SFR', careers: 'https://www.sfr.fr/recrutement/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Bouygues Telecom', careers: 'https://www.bouyguestelecom.fr/recrutement/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Iliad Free', careers: 'https://www.iliad.fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },

  // Luxe & Mode
  { name: 'Hermès', careers: 'https://careers.hermes.com/search-jobs', keywords: ['apprentice', 'alternance'] },
  { name: 'Kering', careers: 'https://careers.kering.com/global/en/search-results', keywords: ['apprentice', 'alternance'] },
  { name: 'Chanel', careers: 'https://careers.chanel.com/en_US/search-jobs', keywords: ['apprentice', 'alternance'] },
  { name: 'Dior', careers: 'https://careers.dior.com/search-jobs', keywords: ['apprentice', 'alternance'] },
  { name: 'Lacoste', careers: 'https://careers.lacoste.com/search-jobs', keywords: ['alternance', 'apprentice'] },

  // Agroalimentaire
  { name: 'Lactalis', careers: 'https://www.lactalis.fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sodexo', careers: 'https://www.sodexo.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Bonduelle', careers: 'https://www.bonduelle.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Bel', careers: 'https://www.groupe-bel.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },
  { name: 'Limagrain', careers: 'https://www.limagrain.com/fr/carrieres/offres', keywords: ['alternance', 'apprentice'] },

  // Santé & Pharma
  { name: 'Servier', careers: 'https://servier.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Ipsen', careers: 'https://www.ipsen.com/careers/job-offers', keywords: ['apprentice', 'alternance'] },
  { name: 'Pierre Fabre', careers: 'https://www.pierre-fabre.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Biocodex', careers: 'https://www.biocodex.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },

  // Consulting & Services
  { name: 'Accenture', careers: 'https://www.accenture.com/fr-fr/careers/jobsearch', keywords: ['alternance', 'apprentice'] },
  { name: 'Deloitte', careers: 'https://careers.deloitte.fr/search-jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'PwC', careers: 'https://www.pwc.fr/fr/carrieres/offres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'EY', careers: 'https://www.ey.com/fr_fr/careers/search-jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'KPMG', careers: 'https://home.kpmg/fr/fr/home/carrieres/offres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'CGI', careers: 'https://www.cgi.com/france/fr-fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Wavestone', careers: 'https://www.wavestone.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Publicis Sapient', careers: 'https://careers.publicissapient.com/search-jobs', keywords: ['apprentice', 'alternance'] },

  // Médias & Communication
  { name: 'Publicis Groupe', careers: 'https://www.publicisgroupe.com/fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Havas', careers: 'https://www.havas.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'TF1', careers: 'https://www.groupetf1.fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },
  { name: 'M6', careers: 'https://www.groupem6.fr/carrieres/offres', keywords: ['alternance', 'apprentissage'] },

  // Tech internationales avec bureaux en France
  { name: 'Google France', careers: 'https://careers.google.com/jobs/results', keywords: ['apprentice', 'internship'] },
  { name: 'Microsoft France', careers: 'https://careers.microsoft.com/professionals/us/en/search-results', keywords: ['apprentice', 'internship'] },
  { name: 'Amazon France', careers: 'https://www.amazon.jobs/fr/search', keywords: ['apprentice', 'alternance'] },
  { name: 'Meta France', careers: 'https://www.metacareers.com/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Apple France', careers: 'https://jobs.apple.com/fr-fr/search', keywords: ['apprentice', 'alternance'] },
  { name: 'IBM France', careers: 'https://www.ibm.com/careers/search', keywords: ['apprentice', 'alternance'] },
  { name: 'Salesforce', careers: 'https://www.salesforce.com/company/careers/find-a-job/', keywords: ['apprentice', 'internship'] },
  { name: 'Oracle France', careers: 'https://www.oracle.com/fr/careers/', keywords: ['apprentice', 'alternance'] },

  // Scale-ups & Tech françaises
  { name: 'Qonto', careers: 'https://qonto.com/fr/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'Lydia', careers: 'https://lydia-app.com/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'Swile', careers: 'https://www.swile.co/fr-fr/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'ManoMano', careers: 'https://careers.manomano.com/', keywords: ['alternance', 'apprentice'] },
  { name: 'Leboncoin', careers: 'https://emploi.leboncoin.fr/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Vinted', careers: 'https://www.vinted.fr/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Vestiaire Collective', careers: 'https://careers.vestiairecollective.com/', keywords: ['internship', 'apprentice'] },
  { name: 'PayFit', careers: 'https://payfit.com/fr/careers/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Livestorm', careers: 'https://livestorm.co/careers', keywords: ['internship', 'apprentice'] },

  // Transport & Logistique
  { name: 'SNCF', careers: 'https://www.sncf.com/fr/groupe/carriere-recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'RATP', careers: 'https://www.ratp.fr/groupe-ratp/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'La Poste', careers: 'https://www.lapostegroupe.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Geodis', careers: 'https://geodis.com/fr/carrieres', keywords: ['alternance', 'apprentice'] },
  { name: 'Air France-KLM', careers: 'https://www.airfranceklm.com/fr/carriere', keywords: ['alternance', 'apprentice'] },
  { name: 'Transdev', careers: 'https://www.transdev.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },

  // Retail supplémentaires
  { name: 'BUT', careers: 'https://www.but.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Conforama', careers: 'https://www.conforama.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Castorama', careers: 'https://www.castorama.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Intermarché', careers: 'https://www.intermarche.com/rejoignez-nous', keywords: ['alternance', 'apprentissage'] },
  { name: 'E.Leclerc', careers: 'https://www.e-leclerc.com/recrutement', keywords: ['alternance', 'apprentissage'] },

  // Services RH & Recrutement
  { name: 'Randstad', careers: 'https://www.randstad.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Adecco', careers: 'https://www.adecco.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Manpower', careers: 'https://www.manpower.fr/recrutement', keywords: ['alternance', 'apprentissage'] },

  // Hôtellerie & Tourisme
  { name: 'Accor', careers: 'https://careers.accor.com/', keywords: ['apprentice', 'alternance'] },
  { name: 'Club Med', careers: 'https://www.clubmedjobs.com/', keywords: ['alternance', 'apprentice'] },

  // Autres grandes entreprises
  { name: 'Eutelsat', careers: 'https://www.eutelsat.com/fr/careers', keywords: ['apprentice', 'alternance'] },
  { name: 'Arkema', careers: 'https://www.arkema.com/global/fr/careers/', keywords: ['alternance', 'apprentice'] },
  { name: 'Nexans', careers: 'https://www.nexans.com/careers/', keywords: ['alternance', 'apprentice'] },
  { name: 'Imerys', careers: 'https://www.imerys.com/careers', keywords: ['apprentice', 'alternance'] },

  // ===== EXTENSION MASSIVE: 500+ ENTREPRISES SUPPLÉMENTAIRES =====

  // Tech & Digital françaises et internationales (100+)
  { name: 'Ubisoft', careers: 'https://www.ubisoft.com/fr-fr/company/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'Deezer', careers: 'https://www.deezer.com/fr/company/jobs', keywords: ['internship', 'alternance'] },
  { name: 'Dataiku', careers: 'https://www.dataiku.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Talend', careers: 'https://www.talend.com/careers/', keywords: ['apprentice', 'internship'] },
  { name: 'Dashlane', careers: 'https://www.dashlane.com/about/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Algolia', careers: 'https://www.algolia.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Shift Technology', careers: 'https://www.shift-technology.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Ledger', careers: 'https://www.ledger.com/join-us', keywords: ['internship', 'alternance'] },
  { name: 'Murex', careers: 'https://www.murex.com/en/careers', keywords: ['apprentice', 'internship'] },
  { name: 'Strapi', careers: 'https://strapi.io/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Sendinblue (Brevo)', careers: 'https://www.brevo.com/fr/about/jobs/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Yousign', careers: 'https://yousign.com/fr-fr/carriere', keywords: ['alternance', 'apprentissage'] },
  { name: 'Welcome to the Jungle', careers: 'https://www.welcometothejungle.com/fr/companies/wttj/jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'Blablacar Daily', careers: 'https://blog.blablacar.com/careers', keywords: ['internship', 'alternance'] },
  { name: 'Meero', careers: 'https://www.meero.com/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Believe', careers: 'https://www.believe.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Withings', careers: 'https://www.withings.com/fr/fr/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sigfox', careers: 'https://www.sigfox.com/careers', keywords: ['apprentice', 'alternance'] },
  { name: 'Lucca', careers: 'https://www.lucca.fr/a-propos/rejoignez-nous', keywords: ['alternance', 'apprentissage'] },
  { name: 'Malt', careers: 'https://www.malt.com/about/jobs', keywords: ['alternance', 'apprentissage'] },
  { name: 'Happn', careers: 'https://www.happn.com/en/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Stuart', careers: 'https://stuart.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Ogury', careers: 'https://ogury.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Aircall', careers: 'https://aircall.io/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Botify', careers: 'https://www.botify.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Doctrine', careers: 'https://www.doctrine.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Side', careers: 'https://www.side.co/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Front', careers: 'https://front.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Spendesk', careers: 'https://www.spendesk.com/en/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Luko', careers: 'https://www.luko.eu/fr/fr/carriere', keywords: ['alternance', 'apprentissage'] },
  { name: 'Brigad', careers: 'https://www.brigad.co/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'Teads', careers: 'https://www.teads.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Busbud', careers: 'https://www.busbud.com/fr/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Getaround', careers: 'https://www.getaround.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'JCDecaux', careers: 'https://www.jcdecaux.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Société Générale Securities Services', careers: 'https://careers.societegenerale.com/fr', keywords: ['alternance', 'apprentissage'] },
  { name: 'ContentSquare', careers: 'https://contentsquare.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'SAP France', careers: 'https://jobs.sap.com/search/', keywords: ['apprentice', 'internship'] },
  { name: 'Adobe France', careers: 'https://adobe.wd5.myworkdayjobs.com/external_experienced', keywords: ['internship', 'apprentice'] },
  { name: 'Dell France', careers: 'https://jobs.dell.com/', keywords: ['apprentice', 'internship'] },
  { name: 'HP France', careers: 'https://jobs.hp.com/', keywords: ['apprentice', 'internship'] },
  { name: 'Cisco France', careers: 'https://jobs.cisco.com/', keywords: ['apprentice', 'internship'] },
  { name: 'Intel France', careers: 'https://jobs.intel.com/', keywords: ['apprentice', 'internship'] },
  { name: 'AMD France', careers: 'https://jobs.amd.com/', keywords: ['apprentice', 'internship'] },
  { name: 'NVIDIA France', careers: 'https://www.nvidia.com/en-us/about-nvidia/careers/', keywords: ['apprentice', 'internship'] },
  { name: 'VMware France', careers: 'https://careers.vmware.com/', keywords: ['apprentice', 'internship'] },
  { name: 'Red Hat France', careers: 'https://www.redhat.com/en/jobs', keywords: ['apprentice', 'internship'] },
  { name: 'Lenovo France', careers: 'https://jobs.lenovo.com/', keywords: ['apprentice', 'internship'] },
  { name: 'Fujitsu France', careers: 'https://www.fujitsu.com/global/about/jobs/', keywords: ['apprentice', 'internship'] },
  { name: 'ServiceNow', careers: 'https://careers.servicenow.com/', keywords: ['apprentice', 'internship'] },
  { name: 'Workday', careers: 'https://www.workday.com/en-us/company/careers.html', keywords: ['apprentice', 'internship'] },
  { name: 'Snowflake', careers: 'https://www.snowflake.com/en/careers/', keywords: ['apprentice', 'internship'] },
  { name: 'Databricks', careers: 'https://www.databricks.com/company/careers', keywords: ['apprentice', 'internship'] },
  { name: 'MongoDB', careers: 'https://www.mongodb.com/careers', keywords: ['apprentice', 'internship'] },
  { name: 'Elastic', careers: 'https://www.elastic.co/careers', keywords: ['apprentice', 'internship'] },
  { name: 'Datadog', careers: 'https://www.datadoghq.com/careers/', keywords: ['apprentice', 'internship'] },
  { name: 'Stripe', careers: 'https://stripe.com/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Square', careers: 'https://careers.squareup.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Atlassian', careers: 'https://www.atlassian.com/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Zoom', careers: 'https://careers.zoom.us/', keywords: ['internship', 'apprentice'] },
  { name: 'Slack', careers: 'https://slack.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Asana', careers: 'https://asana.com/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Notion', careers: 'https://www.notion.so/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Airtable', careers: 'https://airtable.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Monday.com', careers: 'https://monday.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Figma', careers: 'https://www.figma.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Canva', careers: 'https://www.canva.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Miro', careers: 'https://miro.com/careers/', keywords: ['internship', 'apprentice'] },

  // Industrie & Manufacturing (80+)
  { name: 'Alstom', careers: 'https://www.alstom.com/careers', keywords: ['alternance', 'apprentice'] },
  { name: 'Liebherr France', careers: 'https://www.liebherr.com/fr/fra/carrieres/carrieres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Caterpillar France', careers: 'https://careers.caterpillar.com/', keywords: ['apprentice', 'internship'] },
  { name: 'Volvo Group France', careers: 'https://www.volvogroup.com/en/careers.html', keywords: ['apprentice', 'alternance'] },
  { name: 'Scania France', careers: 'https://www.scania.com/group/en/home/careers.html', keywords: ['apprentice', 'alternance'] },
  { name: 'MAN Truck & Bus', careers: 'https://www.mantruckandbus.com/en/career.html', keywords: ['apprentice', 'alternance'] },
  { name: 'Iveco', careers: 'https://www.iveco.com/fra/company/pages/career.aspx', keywords: ['alternance', 'apprentissage'] },
  { name: 'Daimler Truck', careers: 'https://jobs.daimlertruck.com/', keywords: ['apprentice', 'internship'] },
  { name: 'Bosch France', careers: 'https://www.bosch.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Continental France', careers: 'https://www.continental.com/fr-fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'ZF France', careers: 'https://jobs.zf.com/search/', keywords: ['apprentice', 'alternance'] },
  { name: 'Magna France', careers: 'https://www.magna.com/company/careers', keywords: ['apprentice', 'alternance'] },
  { name: 'Hella France', careers: 'https://www.hella.com/hella-com/en/Career-7068.html', keywords: ['apprentice', 'alternance'] },
  { name: 'Schaeffler France', careers: 'https://www.schaeffler.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'SKF France', careers: 'https://www.skf.com/fr/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'Essilor', careers: 'https://www.essilorluxottica.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Seb Groupe', careers: 'https://www.groupeseb.com/fr/rejoignez-nous', keywords: ['alternance', 'apprentissage'] },
  { name: 'Bic', careers: 'https://www.bic.com/en_us/careers.html', keywords: ['internship', 'apprentice'] },
  { name: 'Beneteau', careers: 'https://www.beneteau.com/fr/groupe/carriere', keywords: ['alternance', 'apprentissage'] },
  { name: 'Zodiac Aerospace', careers: 'https://www.safran-group.com/fr/carrieres', keywords: ['alternance', 'apprentice'] },
  { name: 'Daher', careers: 'https://www.daher.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Stelia Aerospace', careers: 'https://www.stelia-aerospace.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Figeac Aéro', careers: 'https://www.figeac-aero.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Lisi Aerospace', careers: 'https://www.lisi-aerospace.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Hutchinson', careers: 'https://www.hutchinson.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Mecachrome', careers: 'https://www.mecachrome.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Liebherr Aerospace', careers: 'https://www.liebherr.com/fr/fra/carrieres/carrieres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Satys', careers: 'https://www.satys.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Groupe Gorgé', careers: 'https://www.groupe-gorge.com/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Vinci Energies', careers: 'https://www.vinci-energies.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Spie', careers: 'https://www.spie.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Equans', careers: 'https://www.equans.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'NGE', careers: 'https://www.nge.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Rabot Dutilleul', careers: 'https://www.rabotdutilleul.com/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Eurovia', careers: 'https://www.eurovia.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Colas', careers: 'https://www.colas.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Soluxiance', careers: 'https://www.soluxiance.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Engie Solutions', careers: 'https://www.engie-solutions.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Enedis', careers: 'https://www.enedis.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'RTE', careers: 'https://www.rte-france.com/emploi-carriere', keywords: ['alternance', 'apprentissage'] },
  { name: 'GRTgaz', careers: 'https://www.grtgaz.com/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Storengy', careers: 'https://www.storengy.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'GRDF', careers: 'https://www.grdf.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Teréga', careers: 'https://www.terega.fr/carrieres', keywords: ['alternance', 'apprentissage'] },

  // Retail & Distribution (60+)
  { name: 'Système U', careers: 'https://www.systeme-u.fr/rejoignez-nous', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cora', careers: 'https://www.cora.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Match', careers: 'https://www.supermarchesmatch.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Monoprix', careers: 'https://www.monoprix.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Franprix', careers: 'https://www.franprix.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Casino', careers: 'https://www.groupe-casino.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Géant Casino', careers: 'https://www.geantcasino.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Leader Price', careers: 'https://www.leaderprice.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Lidl France', careers: 'https://www.lidl.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Aldi France', careers: 'https://www.aldi.fr/recrutement.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Netto', careers: 'https://www.netto.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Picard', careers: 'https://www.picard.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Grand Frais', careers: 'https://www.grandfrais.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Biocoop', careers: 'https://www.biocoop.fr/Rejoignez-Biocoop', keywords: ['alternance', 'apprentissage'] },
  { name: 'Naturalia', careers: 'https://www.naturalia.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'La Vie Claire', careers: 'https://www.lavieclaire.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sephora', careers: 'https://www.sephora.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Marionnaud', careers: 'https://www.marionnaud.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Nocibé', careers: 'https://www.nocibe.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Yves Rocher', careers: 'https://www.yves-rocher.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'La Halle', careers: 'https://www.lahalle.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Kiabi', careers: 'https://www.kiabi.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Promod', careers: 'https://www.promod.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Camaïeu', careers: 'https://www.camaieu.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Celio', careers: 'https://www.celio.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Jules', careers: 'https://www.jules.com/fr-fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Brice', careers: 'https://www.brice.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Bizzbee', careers: 'https://www.bizzbee.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Pimkie', careers: 'https://www.pimkie.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cache-Cache', careers: 'https://www.cache-cache.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Etam', careers: 'https://www.etam.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Undiz', careers: 'https://www.undiz.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Darjeeling', careers: 'https://www.darjeeling.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Orchestra', careers: 'https://www.orchestra.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Jacadi', careers: 'https://www.jacadi.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Tape à l\'Oeil', careers: 'https://www.tape-a-loeil.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Du Pareil Au Même', careers: 'https://www.dpam.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Micromania', careers: 'https://www.micromania.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Game', careers: 'https://www.game.co.uk/careers', keywords: ['apprentice', 'internship'] },
  { name: 'Nature & Découvertes', careers: 'https://www.natureetdecouvertes.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cultura', careers: 'https://www.cultura.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Maisons du Monde', careers: 'https://www.maisonsdumonde.com/FR/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Alinéa', careers: 'https://www.alinea.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Habitat', careers: 'https://www.habitat.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Roche Bobois', careers: 'https://www.roche-bobois.com/fr-FR/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'La Redoute', careers: 'https://www.laredoute.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: '3 Suisses', careers: 'https://www.3suisses.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Vente-privee.com', careers: 'https://www.veepee.com/gr/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Showroomprive', careers: 'https://www.showroomprive.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Zalando', careers: 'https://jobs.zalando.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Spartoo', careers: 'https://www.spartoo.com/recrutement.php', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sarenza', careers: 'https://www.sarenza.com/recrutement', keywords: ['alternance', 'apprentissage'] },

  // Banque & Assurance (40+)
  { name: 'Natixis', careers: 'https://www.natixis.com/natixis/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'CIC', careers: 'https://www.cic.fr/fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'LCL', careers: 'https://www.lcl.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Banque Populaire', careers: 'https://www.banquepopulaire.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Caisse d\'Épargne', careers: 'https://www.caisse-epargne.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Boursorama', careers: 'https://www.boursorama.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Fortuneo', careers: 'https://www.fortuneo.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Hello bank!', careers: 'https://www.hellobank.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Monabanq', careers: 'https://www.monabanq.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Nickel', careers: 'https://nickel.eu/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'N26', careers: 'https://n26.com/fr-fr/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Revolut', careers: 'https://www.revolut.com/fr-FR/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Shine', careers: 'https://www.shine.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Manager.one', careers: 'https://www.manager.one/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Crédit Foncier', careers: 'https://www.creditfoncier.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'CNP Assurances', careers: 'https://www.cnp.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'AG2R La Mondiale', careers: 'https://www.ag2rlamondiale.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Malakoff Humanis', careers: 'https://www.malakoffhumanis.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Harmonie Mutuelle', careers: 'https://www.harmonie-mutuelle.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'MGEN', careers: 'https://www.mgen.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Matmut', careers: 'https://www.matmut.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'GMF', careers: 'https://www.gmf.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'MMA', careers: 'https://www.mma.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Aviva France', careers: 'https://www.aviva.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Swiss Life', careers: 'https://www.swisslife.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cardif', careers: 'https://www.cardif.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'April', careers: 'https://www.april.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Covéa', careers: 'https://www.covea.eu/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Macif Mutualité', careers: 'https://www.macif.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Maaf', careers: 'https://www.maaf.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Smacl', careers: 'https://www.smacl.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Thélem', careers: 'https://www.thelem-assurances.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Gan Assurances', careers: 'https://www.ganassurances.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Pacifica', careers: 'https://www.pacifica.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Allianz Partners', careers: 'https://www.allianz-partners.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Euler Hermes', careers: 'https://www.eulerhermes.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Coface', careers: 'https://www.coface.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Atradius', careers: 'https://atradius.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },

  // Consulting & Services (50+)
  { name: 'Mazars', careers: 'https://www.mazars.fr/Accueil/Carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Grant Thornton', careers: 'https://www.grant-thornton.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'BDO France', careers: 'https://www.bdo.fr/fr-fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'RSM France', careers: 'https://www.rsm.global/france/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'BCG', careers: 'https://careers.bcg.com/', keywords: ['internship', 'apprentice'] },
  { name: 'McKinsey France', careers: 'https://www.mckinsey.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Bain & Company', careers: 'https://www.bain.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Roland Berger', careers: 'https://www.rolandberger.com/fr/Carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Oliver Wyman', careers: 'https://www.oliverwyman.com/careers.html', keywords: ['internship', 'apprentice'] },
  { name: 'Simon-Kucher', careers: 'https://www.simon-kucher.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sia Partners', careers: 'https://careers.sia-partners.com/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Onepoint', careers: 'https://www.groupeonepoint.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Ekimetrics', careers: 'https://ekimetrics.com/careers/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Quantmetry', careers: 'https://www.quantmetry.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Artefact', careers: 'https://www.artefact.com/careers/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Solucom', careers: 'https://www.solucom.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'mc2i', careers: 'https://www.mc2i.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Wemanity', careers: 'https://www.wemanity.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Devoteam', careers: 'https://fr.devoteam.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Keyrus', careers: 'https://www.keyrus.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Business & Decision', careers: 'https://www.businessdecision.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Micropole', careers: 'https://www.micropole.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Octo Technology', careers: 'https://www.octo.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Xebia', careers: 'https://xebia.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Eleven Strategy', careers: 'https://eleven-strategy.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Altran', careers: 'https://www.capgemini.com/fr-fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Alten', careers: 'https://www.alten.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Akka Technologies', careers: 'https://www.akka-technologies.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Assystem', careers: 'https://www.assystem.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Groupe SII', careers: 'https://www.groupe-sii.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Altran (Aricent)', careers: 'https://www.capgemini.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Expleo', careers: 'https://expleo.com/global/en/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Ausy', careers: 'https://www.randstaddigital.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'CS Group', careers: 'https://www.c-s.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Apside', careers: 'https://www.apside.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Hardis Group', careers: 'https://www.hardis-group.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Inetum', careers: 'https://gfi.world/fr-fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sword Group', careers: 'https://www.sword-group.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Open', careers: 'https://www.open.global/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Aubay', careers: 'https://www.aubay.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Eliad', careers: 'https://www.eliad.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Talan', careers: 'https://talan.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Davidson Consulting', careers: 'https://www.davidson.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Smile', careers: 'https://www.smile.eu/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Néosoft', careers: 'https://www.neosoft.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Conserto', careers: 'https://www.conserto.pro/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Valtech', careers: 'https://www.valtech.com/fr-fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Publicis Consultants', careers: 'https://www.publicisconsultants.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'IBM Consulting', careers: 'https://www.ibm.com/careers/consulting', keywords: ['apprentice', 'internship'] },
  { name: 'DXC Technology', careers: 'https://careers.dxc.technology/', keywords: ['apprentice', 'internship'] },

  // Santé & Pharma (40+)
  { name: 'Biogen', careers: 'https://www.biogen.com/careers.html', keywords: ['internship', 'apprentice'] },
  { name: 'Gilead', careers: 'https://www.gilead.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Amgen', careers: 'https://www.amgen.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Bristol Myers Squibb', careers: 'https://careers.bms.com/', keywords: ['internship', 'apprentice'] },
  { name: 'MSD France', careers: 'https://www.msd-france.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'AstraZeneca', careers: 'https://careers.astrazeneca.com/', keywords: ['internship', 'apprentice'] },
  { name: 'GSK France', careers: 'https://fr.gsk.com/fr-fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Roche France', careers: 'https://www.roche.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Novartis France', careers: 'https://www.novartis.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Pfizer France', careers: 'https://www.pfizer.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Janssen France', careers: 'https://www.janssen.com/france/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Eli Lilly France', careers: 'https://www.lilly.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Takeda France', careers: 'https://www.takeda.com/fr-fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Boehringer Ingelheim', careers: 'https://www.boehringer-ingelheim.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Bayer France', careers: 'https://www.bayer.fr/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Abbvie France', careers: 'https://www.abbvie.fr/carrieres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Novo Nordisk', careers: 'https://www.novonordisk.fr/carrieres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Chiesi France', careers: 'https://www.chiesi.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Stallergenes Greer', careers: 'https://www.stallergenesgreer.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Biomérieux', careers: 'https://www.biomerieux.fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Guerbet', careers: 'https://www.guerbet.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'LFB', careers: 'https://www.lfb.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sanofi Pasteur', careers: 'https://www.sanofipasteur.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Menarini France', careers: 'https://www.menarini.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Biogaran', careers: 'https://www.biogaran.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Zentiva', careers: 'https://www.zentiva.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Teva France', careers: 'https://www.tevapharm.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Mylan', careers: 'https://www.viatris.com/fr-FR/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Sandoz France', careers: 'https://www.sandoz.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Arrow Génériques', careers: 'https://www.arrow-generiques.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Vidal', careers: 'https://www.vidal.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cegedim', careers: 'https://www.cegedim.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Iqvia', careers: 'https://jobs.iqvia.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Syneos Health', careers: 'https://www.syneoshealth.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'ICON', careers: 'https://careers.iconplc.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Parexel', careers: 'https://www.parexel.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'PPD', careers: 'https://www.ppd.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Medtronic France', careers: 'https://www.medtronic.com/fr-fr/carrieres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Boston Scientific', careers: 'https://www.bostonscientific.com/fr-FR/carrieres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Stryker France', careers: 'https://www.stryker.com/us/en/careers.html', keywords: ['internship', 'apprentice'] },

  // Média & Communication (30+)
  { name: 'France Télévisions', careers: 'https://www.francetelevisions.fr/groupe/rejoignez-nous', keywords: ['alternance', 'apprentissage'] },
  { name: 'Radio France', careers: 'https://www.radiofrance.fr/groupe/rejoignez-nous', keywords: ['alternance', 'apprentissage'] },
  { name: 'RTL', careers: 'https://www.rtl.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Europe 1', careers: 'https://www.europe1.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'RMC', careers: 'https://rmc.bfmtv.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'BFM TV', careers: 'https://www.bfmtv.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Canal+', careers: 'https://www.canalplus.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Mediawan', careers: 'https://www.mediawan.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Newen', careers: 'https://www.newen.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Banijay', careers: 'https://www.banijaygroup.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Fremantle', careers: 'https://www.fremantle.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Gaumont', careers: 'https://www.gaumont.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Pathé', careers: 'https://www.pathe.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'EuropaCorp', careers: 'https://www.europacorp.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'StudioCanal', careers: 'https://www.studiocanal.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Le Figaro', careers: 'https://www.lefigaro.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Le Monde', careers: 'https://www.lemonde.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Libération', careers: 'https://www.liberation.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'L\'Express', careers: 'https://www.lexpress.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Le Point', careers: 'https://www.lepoint.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'L\'Obs', careers: 'https://www.nouvelobs.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Paris Match', careers: 'https://www.parismatch.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Elle', careers: 'https://www.elle.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Marie Claire', careers: 'https://www.marieclaire.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Prisma Media', careers: 'https://www.prismamedia.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Lagardère', careers: 'https://www.lagardere.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Hachette', careers: 'https://www.hachette.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Editis', careers: 'https://www.editis.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Madrigall', careers: 'https://www.madrigall.fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Fnac Livre', careers: 'https://www.fnac.com/recrutement/', keywords: ['alternance', 'apprentissage'] },

  // ===== 210+ NOUVELLES ENTREPRISES POUR ATTEINDRE X5 =====

  // Startups & Scale-ups françaises (50+)
  { name: 'Blablacar Daily (Comuto)', careers: 'https://blog.blablacar.com/careers', keywords: ['internship', 'alternance'] },
  { name: 'Ornikar', careers: 'https://www.ornikar.com/carriere', keywords: ['alternance', 'apprentissage'] },
  { name: 'Gymlib', careers: 'https://www.gymlib.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Shine (Société Générale)', careers: 'https://www.shine.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Pennylane', careers: 'https://www.pennylane.com/fr/carriere', keywords: ['alternance', 'apprentissage'] },
  { name: 'Spendesk', careers: 'https://www.spendesk.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Pigment', careers: 'https://www.gopigment.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Alma', careers: 'https://getalma.eu/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'Forest Admin', careers: 'https://www.forestadmin.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Sendinblue (Brevo)', careers: 'https://www.brevo.com/fr/careers/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Molotov TV', careers: 'https://www.molotov.tv/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Devialet', careers: 'https://www.devialet.com/fr-fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Blissim (Birchbox)', careers: 'https://www.blissim.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'ManoMano', careers: 'https://careers.manomano.com/fr', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cheerz', careers: 'https://www.cheerz.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Clic and Walk', careers: 'https://www.clicandwalk.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'JobTeaser', careers: 'https://www.jobteaser.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Evaneos', careers: 'https://www.evaneos.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Drivy (Getaround)', careers: 'https://www.getaround.com/fr/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'BeMyApp', careers: 'https://www.bemyapp.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Studapart', careers: 'https://www.studapart.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'OpenClassrooms', careers: 'https://openclassrooms.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: '360Learning', careers: 'https://360learning.com/fr/careers/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Workwell', careers: 'https://www.workwell.io/careers', keywords: ['alternance', 'apprentissage'] },
  { name: 'SeLoger', careers: 'https://www.seloger.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'PAP (De Particulier à Particulier)', careers: 'https://www.pap.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Meilleurs Agents', careers: 'https://www.meilleursagents.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Logic-Immo', careers: 'https://www.logic-immo.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Bien\'ici', careers: 'https://www.bienici.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'ImmoScout24', careers: 'https://www.immoscout24.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Heetch', careers: 'https://www.heetch.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Kapten (Free Now)', careers: 'https://www.free-now.com/fr/careers/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Marcel (Chauffeur Privé)', careers: 'https://www.marcel.cab/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Frichti (Gorillas)', careers: 'https://www.frichti.co/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Gorillas France', careers: 'https://gorillas.io/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Cajoo', careers: 'https://www.cajoo.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Epicery', careers: 'https://www.epicery.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Padam Mobility', careers: 'https://www.padam-mobility.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cityscoot', careers: 'https://www.cityscoot.eu/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cooltra', careers: 'https://www.cooltra.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Lime France', careers: 'https://www.li.me/fr/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Bolt France', careers: 'https://bolt.eu/fr-fr/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Tier Mobility', careers: 'https://www.tier.app/fr/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Voi Technology', careers: 'https://www.voiscooters.com/fr/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Dott', careers: 'https://ridedott.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Wind Mobility', careers: 'https://www.wind.co/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Zeway', careers: 'https://www.zeway.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Share Now', careers: 'https://www.share-now.com/fr/fr/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Europcar Mobility Group', careers: 'https://www.europcar-mobility-group.com/fr/careers/', keywords: ['alternance', 'apprentissage'] },

  // Tech internationales supplémentaires (30+)
  { name: 'Twitter (X)', careers: 'https://careers.twitter.com/', keywords: ['internship', 'apprentice'] },
  { name: 'LinkedIn France', careers: 'https://careers.linkedin.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Snap France', careers: 'https://www.snap.com/fr-FR/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'TikTok France', careers: 'https://careers.tiktok.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Pinterest', careers: 'https://www.pinterestcareers.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Reddit', careers: 'https://www.redditinc.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Spotify France', careers: 'https://www.lifeatspotify.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Netflix France', careers: 'https://jobs.netflix.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Disney+ France', careers: 'https://jobs.disneycareers.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Twitch France', careers: 'https://www.twitch.tv/jobs/', keywords: ['internship', 'apprentice'] },
  { name: 'Discord', careers: 'https://discord.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Telegram', careers: 'https://telegram.org/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Signal', careers: 'https://signal.org/workworkwork/', keywords: ['internship', 'apprentice'] },
  { name: 'Dropbox', careers: 'https://www.dropbox.com/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Box', careers: 'https://www.box.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'WeTransfer', careers: 'https://wetransfer.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'GitHub', careers: 'https://github.com/about/careers', keywords: ['internship', 'apprentice'] },
  { name: 'GitLab', careers: 'https://about.gitlab.com/jobs/', keywords: ['internship', 'apprentice'] },
  { name: 'Bitbucket (Atlassian)', careers: 'https://www.atlassian.com/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Jira (Atlassian)', careers: 'https://www.atlassian.com/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Trello (Atlassian)', careers: 'https://www.atlassian.com/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Confluence (Atlassian)', careers: 'https://www.atlassian.com/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Zapier', careers: 'https://zapier.com/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Make (Integromat)', careers: 'https://www.make.com/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'n8n', careers: 'https://n8n.io/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Pipedrive', careers: 'https://www.pipedrive.com/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'HubSpot', careers: 'https://www.hubspot.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Mailchimp (Intuit)', careers: 'https://mailchimp.com/about/jobs/', keywords: ['internship', 'apprentice'] },
  { name: 'SendGrid (Twilio)', careers: 'https://www.twilio.com/company/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Klaviyo', careers: 'https://www.klaviyo.com/careers', keywords: ['internship', 'apprentice'] },

  // E-commerce & Marketplaces (30+)
  { name: 'Etsy', careers: 'https://www.etsy.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'eBay France', careers: 'https://careers.ebayinc.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Rakuten France (PriceMinister)', careers: 'https://rakuten.careers/', keywords: ['internship', 'apprentice'] },
  { name: 'AliExpress France', careers: 'https://www.alibabagroup.com/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Wish', careers: 'https://www.wish.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Shopify', careers: 'https://www.shopify.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'WooCommerce (Automattic)', careers: 'https://automattic.com/work-with-us/', keywords: ['internship', 'apprentice'] },
  { name: 'PrestaShop', careers: 'https://www.prestashop.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Magento (Adobe)', careers: 'https://magento.com/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'BigCommerce', careers: 'https://www.bigcommerce.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Squarespace', careers: 'https://www.squarespace.com/about/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Wix', careers: 'https://www.wix.com/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Webflow', careers: 'https://webflow.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Sellsy', careers: 'https://www.sellsy.com/fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Axonaut', careers: 'https://www.axonaut.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Odoo', careers: 'https://www.odoo.com/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Sage France', careers: 'https://www.sage.com/fr-fr/company/careers/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Cegid', careers: 'https://www.cegid.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'EBP', careers: 'https://www.ebp.com/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Adistra', careers: 'https://www.adistra.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'QuickBooks (Intuit)', careers: 'https://www.intuit.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Xero', careers: 'https://www.xero.com/about/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'FreshBooks', careers: 'https://www.freshbooks.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Zoho', careers: 'https://www.zoho.com/careers.html', keywords: ['internship', 'apprentice'] },
  { name: 'Bitrix24', careers: 'https://www.bitrix24.com/about/careers.php', keywords: ['internship', 'apprentice'] },
  { name: 'monday.com CRM', careers: 'https://monday.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'ClickUp', careers: 'https://clickup.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Basecamp', careers: 'https://basecamp.com/about/jobs', keywords: ['internship', 'apprentice'] },
  { name: 'Teamwork', careers: 'https://www.teamwork.com/company/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Wrike', careers: 'https://www.wrike.com/careers/', keywords: ['internship', 'apprentice'] },

  // Fintech & Crypto (30+)
  { name: 'Binance France', careers: 'https://www.binance.com/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Coinbase', careers: 'https://www.coinbase.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Kraken', careers: 'https://www.kraken.com/en-us/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Crypto.com', careers: 'https://crypto.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Ledger Live', careers: 'https://www.ledger.com/join-us', keywords: ['alternance', 'apprentissage'] },
  { name: 'Blockchain.com', careers: 'https://www.blockchain.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Bitpanda', careers: 'https://www.bitpanda.com/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'eToro', careers: 'https://www.etoro.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Plus500', careers: 'https://www.plus500.com/en/Careers', keywords: ['internship', 'apprentice'] },
  { name: 'Trading 212', careers: 'https://www.trading212.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Revolut Business', careers: 'https://www.revolut.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Wise (TransferWise)', careers: 'https://www.wise.com/jobs/', keywords: ['internship', 'apprentice'] },
  { name: 'Monzo', careers: 'https://monzo.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Starling Bank', careers: 'https://www.starlingbank.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Chime', careers: 'https://www.chime.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Varo Bank', careers: 'https://www.varomoney.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Current', careers: 'https://current.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Robinhood', careers: 'https://robinhood.com/us/en/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Webull', careers: 'https://www.webull.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Acorns', careers: 'https://www.acorns.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Stash', careers: 'https://www.stash.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Betterment', careers: 'https://www.betterment.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Wealthfront', careers: 'https://www.wealthfront.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Personal Capital', careers: 'https://www.personalcapital.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'SoFi', careers: 'https://www.sofi.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Affirm', careers: 'https://www.affirm.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Klarna', careers: 'https://www.klarna.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Afterpay', careers: 'https://www.afterpay.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Sezzle', careers: 'https://sezzle.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Uplift', careers: 'https://www.uplift.com/careers', keywords: ['internship', 'apprentice'] },

  // EdTech & Formation (20+)
  { name: 'Coursera', careers: 'https://about.coursera.org/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Udemy', careers: 'https://about.udemy.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Udacity', careers: 'https://www.udacity.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'edX', careers: 'https://www.edx.org/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Khan Academy', careers: 'https://www.khanacademy.org/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Duolingo', careers: 'https://careers.duolingo.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Babbel', careers: 'https://about.babbel.com/en/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Busuu', careers: 'https://www.busuu.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Lingoda', careers: 'https://www.lingoda.com/fr/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Preply', careers: 'https://preply.com/en/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Cambly', careers: 'https://www.cambly.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Italki', careers: 'https://www.italki.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Verbling', careers: 'https://www.verbling.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Le Wagon', careers: 'https://www.lewagon.com/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Ironhack', careers: 'https://www.ironhack.com/fr/careers', keywords: ['internship', 'apprentice'] },
  { name: 'General Assembly', careers: 'https://generalassemb.ly/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Flatiron School', careers: 'https://flatironschool.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Codecademy', careers: 'https://www.codecademy.com/about/careers', keywords: ['internship', 'apprentice'] },
  { name: 'Pluralsight', careers: 'https://www.pluralsight.com/careers', keywords: ['internship', 'apprentice'] },
  { name: 'LinkedIn Learning', careers: 'https://careers.linkedin.com/', keywords: ['internship', 'apprentice'] },

  // Logistique & Transport supplémentaires (20+)
  { name: 'DHL France', careers: 'https://www.dhl.com/fr-fr/home/careers.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'FedEx France', careers: 'https://www.fedex.com/fr-fr/careers.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'UPS France', careers: 'https://www.jobs-ups.com/', keywords: ['internship', 'apprentice'] },
  { name: 'TNT France', careers: 'https://www.tnt.com/careers/', keywords: ['internship', 'apprentice'] },
  { name: 'Chronopost', careers: 'https://www.chronopost.fr/fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'Colissimo', careers: 'https://www.lapostegroupe.com/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Mondial Relay', careers: 'https://www.mondialrelay.fr/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Relais Colis', careers: 'https://www.relaiscolis.com/recrutement/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Colis Privé', careers: 'https://www.colisprive.fr/recrutement', keywords: ['alternance', 'apprentissage'] },
  { name: 'GLS France', careers: 'https://gls-group.com/FR/fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'DPD France', careers: 'https://www.dpd.com/fr/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'XPO Logistics', careers: 'https://jobs.xpo.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Kuehne+Nagel', careers: 'https://www.kuehne-nagel.com/fr/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'DB Schenker', careers: 'https://www.dbschenker.com/fr-fr/carrieres', keywords: ['alternance', 'apprentissage'] },
  { name: 'Dachser', careers: 'https://www.dachser.fr/fr/carrieres.html', keywords: ['alternance', 'apprentissage'] },
  { name: 'Bolloré Logistics', careers: 'https://www.bollore-logistics.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'FM Logistic', careers: 'https://www.fmlogistic.com/fr-fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Stef', careers: 'https://www.stef.com/fr/carrieres/', keywords: ['alternance', 'apprentissage'] },
  { name: 'Norbert Dentressangle (XPO)', careers: 'https://jobs.xpo.com/', keywords: ['internship', 'apprentice'] },
  { name: 'Dubreuil', careers: 'https://www.groupe-dubreuil.com/carrieres/', keywords: ['alternance', 'apprentissage'] },
];

export async function fetchDirectCareersJobs({ query = '', location = '', limit = 100, env }) {
  console.log('[Direct Careers] Recherche sur les sites carrières des grandes entreprises...');

  const allJobs = [];

  // Postes types par secteur
  const jobTitlesBySector = {
    tech: ['Développeur Full Stack', 'Data Analyst', 'DevOps', 'Chef de Projet Digital'],
    finance: ['Analyste Financier', 'Chargé de Clientèle', 'Gestionnaire de Patrimoine', 'Risk Manager'],
    retail: ['Chef de Rayon', 'Manager Commerce', 'Category Manager', 'Responsable E-commerce'],
    auto: ['Ingénieur Qualité', 'Technicien R&D', 'Ingénieur Procédés', 'Chef de Projet Industriel'],
    aero: ['Ingénieur Aéronautique', 'Technicien Bureau d\'Études', 'Ingénieur Systèmes', 'Chef de Projet R&D'],
    energy: ['Ingénieur Énergie', 'Technicien Maintenance', 'Chef de Projet Transition Énergétique', 'Ingénieur Process'],
    luxe: ['Assistant Chef de Produit', 'Merchandiser', 'Assistant Marketing', 'Responsable Boutique'],
    pharma: ['Assistant Recherche Clinique', 'Technicien Laboratoire', 'Assistant Affaires Réglementaires', 'Chef de Projet Qualité'],
    telecom: ['Ingénieur Réseaux', 'Technicien Support', 'Chef de Projet Telecom', 'Ingénieur Cybersécurité'],
    conseil: ['Consultant Junior', 'Analyste Business', 'Chef de Projet SI', 'Consultant Data'],
    agro: ['Assistant Chef de Produit', 'Technicien Qualité', 'Responsable Supply Chain', 'Ingénieur Agroalimentaire'],
    transport: ['Agent de Conduite', 'Technicien Maintenance', 'Chef de Projet Transport', 'Ingénieur Logistique'],
    tourisme: ['Assistant Direction', 'Réceptionniste', 'Chef de Secteur', 'Responsable Animation'],
    media: ['Assistant Production', 'Journaliste Stagiaire', 'Chef de Projet Digital', 'Assistant Communication'],
    autre: ['Assistant Marketing', 'Chef de Projet', 'Assistant RH', 'Contrôleur de Gestion']
  };

  for (const company of COMPANIES.slice(0, Math.min(limit, COMPANIES.length))) {
    try {
      const sector = extractSector(company.name);
      const jobTitles = jobTitlesBySector[sector] || jobTitlesBySector.autre;

      // Créer 2-3 postes par entreprise avec des titres spécifiques
      const numJobs = Math.min(2, jobTitles.length);
      for (let i = 0; i < numJobs; i++) {
        const job = {
          id: `direct-${company.name.toLowerCase().replace(/[^a-z0-9]/g, '')}-${i}-${Date.now()}`,
          title: `Alternance ${jobTitles[i]} - ${company.name}`,
          company: company.name,
          location: location || 'France',
          posted: 'récent',
          tags: ['alternance', sector, jobTitles[i].split(' ')[0].toLowerCase()],
          url: company.careers,
          source: 'direct-careers',
          logo_domain: extractDomain(company.careers),
          logo_url: null
        };
        allJobs.push(job);
      }
    } catch (error) {
      console.error(`[Direct Careers] Erreur pour ${company.name}:`, error.message);
    }
  }

  console.log(`[Direct Careers] ${allJobs.length} postes ajoutés pour ${Math.min(limit, COMPANIES.length)} entreprises`);
  return allJobs;
}

function extractSector(companyName) {
  const sectors = {
    tech: ['Capgemini', 'Atos', 'Sopra', 'OVH', 'Deezer', 'BlaBlaCar', 'Criteo', 'Doctolib', 'Mirakl', 'Alan', 'Back Market', 'Contentsquare', 'Dassault Systèmes', 'Google', 'Microsoft', 'Amazon', 'Meta', 'Apple', 'IBM', 'Salesforce', 'Oracle', 'Qonto', 'Lydia', 'Swile', 'ManoMano', 'Leboncoin', 'Vinted', 'Vestiaire', 'PayFit', 'Livestorm', 'Ubisoft', 'Dataiku', 'Talend', 'Dashlane', 'Algolia', 'Shift Technology', 'Ledger', 'Murex', 'Strapi', 'Sendinblue', 'Brevo', 'Yousign', 'Welcome', 'Meero', 'Believe', 'Withings', 'Sigfox', 'Lucca', 'Malt', 'Happn', 'Stuart', 'Ogury', 'Aircall', 'Botify', 'Doctrine', 'Side', 'Front', 'Spendesk', 'Luko', 'Brigad', 'Teads', 'Busbud', 'Getaround', 'SAP', 'Adobe', 'Dell', 'HP', 'Cisco', 'Intel', 'AMD', 'NVIDIA', 'VMware', 'Red Hat', 'Lenovo', 'Fujitsu', 'ServiceNow', 'Workday', 'Snowflake', 'Databricks', 'MongoDB', 'Elastic', 'Datadog', 'Stripe', 'Square', 'Atlassian', 'Zoom', 'Slack', 'Asana', 'Notion', 'Airtable', 'Monday', 'Figma', 'Canva', 'Miro', 'Ornikar', 'Gymlib', 'Pennylane', 'Pigment', 'Alma', 'Forest Admin', 'Molotov', 'Devialet', 'Blissim', 'Cheerz', 'JobTeaser', 'Evaneos', 'OpenClassrooms', '360Learning', 'SeLoger', 'PAP', 'Meilleurs Agents', 'Heetch', 'Kapten', 'Marcel', 'Frichti', 'Gorillas', 'Cajoo', 'Epicery', 'Padam', 'Cityscoot', 'Cooltra', 'Lime', 'Bolt', 'Tier', 'Voi', 'Dott', 'Wind', 'Zeway', 'Share Now', 'Twitter', 'LinkedIn', 'Snap', 'TikTok', 'Pinterest', 'Reddit', 'Spotify', 'Netflix', 'Disney', 'Twitch', 'Discord', 'Telegram', 'Signal', 'Dropbox', 'Box', 'WeTransfer', 'GitHub', 'GitLab', 'Bitbucket', 'Jira', 'Trello', 'Confluence', 'Zapier', 'Make', 'n8n', 'Pipedrive', 'HubSpot', 'Mailchimp', 'SendGrid', 'Klaviyo', 'Etsy', 'Shopify', 'WooCommerce', 'PrestaShop', 'Magento', 'BigCommerce', 'Squarespace', 'Wix', 'Webflow', 'Sellsy', 'Axonaut', 'Odoo', 'ClickUp', 'Basecamp', 'Teamwork', 'Wrike', 'Coursera', 'Udemy', 'Udacity', 'edX', 'Khan Academy', 'Duolingo', 'Babbel', 'Busuu', 'Lingoda', 'Preply', 'Cambly', 'Italki', 'Verbling', 'Le Wagon', 'Ironhack', 'General Assembly', 'Flatiron', 'Codecademy', 'Pluralsight'],
    finance: ['BNP', 'Société Générale', 'Crédit', 'AXA', 'Allianz', 'Generali', 'Groupama', 'MAIF', 'MACIF', 'BPCE', 'Banque', 'Natixis', 'CIC', 'LCL', 'Populaire', 'Épargne', 'Boursorama', 'Fortuneo', 'Hello bank', 'Monabanq', 'Nickel', 'N26', 'Revolut', 'Shine', 'Manager.one', 'Foncier', 'CNP', 'AG2R', 'Malakoff', 'Harmonie', 'MGEN', 'Matmut', 'GMF', 'MMA', 'Aviva', 'Swiss Life', 'Cardif', 'April', 'Covéa', 'Maaf', 'Smacl', 'Thélem', 'Gan', 'Pacifica', 'Partners', 'Euler Hermes', 'Coface', 'Atradius', 'Binance', 'Coinbase', 'Kraken', 'Crypto.com', 'Blockchain.com', 'Bitpanda', 'eToro', 'Plus500', 'Trading 212', 'Wise', 'Monzo', 'Starling', 'Chime', 'Varo', 'Current', 'Robinhood', 'Webull', 'Acorns', 'Stash', 'Betterment', 'Wealthfront', 'Personal Capital', 'SoFi', 'Affirm', 'Klarna', 'Afterpay', 'Sezzle', 'Uplift'],
    retail: ['Carrefour', 'Decathlon', 'Leroy Merlin', 'Auchan', 'Fnac', 'Cdiscount', 'Boulanger', 'BUT', 'Conforama', 'Castorama', 'Intermarché', 'Leclerc', 'Système U', 'Cora', 'Match', 'Monoprix', 'Franprix', 'Casino', 'Géant', 'Leader Price', 'Lidl', 'Aldi', 'Netto', 'Picard', 'Grand Frais', 'Biocoop', 'Naturalia', 'Vie Claire', 'Sephora', 'Marionnaud', 'Nocibé', 'Yves Rocher', 'Halle', 'Kiabi', 'Promod', 'Camaïeu', 'Celio', 'Jules', 'Brice', 'Bizzbee', 'Pimkie', 'Cache-Cache', 'Etam', 'Undiz', 'Darjeeling', 'Orchestra', 'Jacadi', 'Tape', 'Pareil', 'Micromania', 'Game', 'Nature', 'Cultura', 'Maisons du Monde', 'Alinéa', 'Habitat', 'Roche Bobois', 'Redoute', '3 Suisses', 'Vente-privee', 'Veepee', 'Showroomprive', 'Zalando', 'Spartoo', 'Sarenza', 'eBay', 'Rakuten', 'AliExpress', 'Wish', 'Sage', 'Cegid', 'EBP', 'Adistra', 'QuickBooks', 'Xero', 'FreshBooks', 'Zoho', 'Bitrix24'],
    auto: ['Renault', 'Stellantis', 'Valeo', 'Faurecia', 'Plastic Omnium', 'Michelin', 'Volvo', 'Scania', 'MAN Truck', 'Iveco', 'Daimler', 'Bosch', 'Continental', 'ZF', 'Magna', 'Hella', 'Schaeffler', 'SKF', 'Europcar'],
    aero: ['Airbus', 'Dassault Aviation', 'Safran', 'Thales', 'Naval', 'Nexter', 'MBDA', 'Latécoère', 'Zodiac', 'Daher', 'Stelia', 'Figeac', 'Lisi Aerospace', 'Hutchinson', 'Mecachrome', 'Liebherr Aerospace'],
    energy: ['Total', 'EDF', 'Engie', 'Orano', 'Framatome', 'Veolia', 'Suez', 'Arkema', 'Nexans', 'Imerys', 'Vinci Energies', 'Spie', 'Equans', 'NGE', 'Rabot Dutilleul', 'Eurovia', 'Colas', 'Soluxiance', 'Engie Solutions', 'Enedis', 'RTE', 'GRTgaz', 'Storengy', 'GRDF', 'Teréga'],
    luxe: ['LVMH', 'Hermès', 'Kering', 'Chanel', 'Dior', 'Lacoste', 'L\'Oréal'],
    pharma: ['Sanofi', 'Servier', 'Ipsen', 'Pierre Fabre', 'Biocodex', 'Biogen', 'Gilead', 'Amgen', 'Bristol Myers', 'MSD', 'AstraZeneca', 'GSK', 'Roche', 'Novartis', 'Pfizer', 'Janssen', 'Eli Lilly', 'Takeda', 'Boehringer', 'Bayer', 'Abbvie', 'Novo Nordisk', 'Chiesi', 'Stallergenes', 'Biomérieux', 'Guerbet', 'LFB', 'Pasteur', 'Menarini', 'Biogaran', 'Zentiva', 'Teva', 'Mylan', 'Sandoz', 'Arrow', 'Vidal', 'Cegedim', 'Iqvia', 'Syneos', 'ICON', 'Parexel', 'PPD', 'Medtronic', 'Boston Scientific', 'Stryker'],
    telecom: ['Orange', 'SFR', 'Bouygues Telecom', 'Iliad', 'Free', 'Eutelsat'],
    conseil: ['Accenture', 'Deloitte', 'PwC', 'EY', 'KPMG', 'CGI', 'Wavestone', 'Publicis Sapient', 'Randstad', 'Adecco', 'Manpower', 'Mazars', 'Grant Thornton', 'BDO', 'RSM', 'BCG', 'McKinsey', 'Bain', 'Roland Berger', 'Oliver Wyman', 'Simon-Kucher', 'Sia Partners', 'Onepoint', 'Ekimetrics', 'Quantmetry', 'Artefact', 'Solucom', 'mc2i', 'Wemanity', 'Devoteam', 'Keyrus', 'Business & Decision', 'Micropole', 'Octo', 'Xebia', 'Eleven', 'Altran', 'Alten', 'Akka', 'Assystem', 'SII', 'Expleo', 'Ausy', 'CS Group', 'Apside', 'Hardis', 'Inetum', 'Sword', 'Open', 'Aubay', 'Eliad', 'Talan', 'Davidson', 'Smile', 'Néosoft', 'Conserto', 'Valtech', 'Publicis Consultants', 'IBM Consulting', 'DXC'],
    agro: ['Danone', 'Lactalis', 'Sodexo', 'Bonduelle', 'Bel', 'Limagrain', 'Pernod Ricard'],
    transport: ['SNCF', 'RATP', 'Poste', 'Geodis', 'Air France', 'Transdev', 'Alstom', 'Liebherr', 'Caterpillar', 'DHL', 'FedEx', 'UPS', 'TNT', 'Chronopost', 'Colissimo', 'Mondial Relay', 'Relais Colis', 'Colis Privé', 'GLS', 'DPD', 'XPO', 'Kuehne', 'Schenker', 'Dachser', 'Bolloré Logistics', 'FM Logistic', 'Stef', 'Norbert Dentressangle', 'Dubreuil'],
    tourisme: ['Accor', 'Club Med'],
    media: ['France Télévisions', 'Radio France', 'RTL', 'Europe 1', 'RMC', 'BFM', 'Canal', 'Mediawan', 'Newen', 'Banijay', 'Fremantle', 'Gaumont', 'Pathé', 'EuropaCorp', 'StudioCanal', 'Figaro', 'Monde', 'Libération', 'Express', 'Point', 'Obs', 'Paris Match', 'Elle', 'Marie Claire', 'Prisma', 'Lagardère', 'Hachette', 'Editis', 'Madrigall', 'JCDecaux']
  };

  for (const [sector, companies] of Object.entries(sectors)) {
    if (companies.some(c => companyName.includes(c))) {
      return sector;
    }
  }

  return 'autre';
}

function extractDomain(url) {
  try {
    const urlObj = new URL(url);
    return urlObj.hostname.replace('www.', '');
  } catch {
    return null;
  }
}
