name = "refresh-cron"
main = "index.js"
compatibility_date = "2024-12-01"

[triggers]
# 05:00, 13:00, 21:00 UTC
crons = ["0 5 * * *", "0 13 * * *", "0 21 * * *"]

[vars]
BASE_URL = "https://www.alternant-talent.com"
